#!/bin/bash

DIR=$1; cd $DIR

#############################
# total of ncl files
#############################

NFILES=`find . -type f \( -iname "*.ncl" ! -iname ".*" \) | grep -c ""`

echo "Total of *.ncl files: $NFILES."

#############################
# total of ncl files created by ncl eclipse
#############################

NNE=`find . -type f \( -iname "*.ncl" ! -iname ".*" \) | xargs grep -c "Generated by NCL Eclipse" | sed "s/.*:\(.*\)/\1/g" | paste -sd+ | bc`

echo "Total of *.ncl files created by NCL Eclipse: $NNE/$NFILES."
echo

#############################
# total of max="" attribute
#############################

NMAX=`find . -type f \( -iname "*.ncl" ! -iname ".*" \) | xargs grep -c "max=" | sed "s/.*:\(.*\)/\1/g" | paste -sd+ | bc`

echo "Total of max=\"\" attribute: $NMAX."

#############################
# total of max="unbounded" attribute
#############################

NMAXU=`find . -type f \( -iname "*.ncl" ! -iname ".*" \) | xargs grep -c "max=\"unbounded\"" | sed "s/.*:\(.*\)/\1/g" | paste -sd+ | bc`

echo "Total of max=\"unbounded\" attribute: $NMAXU/$NMAX."
echo

#############################
# total of min="" attribute
#############################

NMIN=`find . -type f \( -iname "*.ncl" ! -iname ".*" \) | xargs grep -c "min=" | sed "s/.*:\(.*\)/\1/g" | paste -sd+ | bc`

echo "Total of min=\"\" attribute: $NMIN".

#############################
# total of min="0" attribute
#############################

NMINZ=`find . -type f \( -iname "*.ncl" ! -iname ".*" \) | xargs grep -c "min=\"0\"" | sed "s/.*:\(.*\)/\1/g" | paste -sd+ | bc`

echo "Total of min=\"0\" attribute: $NMINZ/$NMIN."
echo

#############################
# total of qualifier="" attribute
#############################

NQ=`find . -type f \( -iname "*.ncl" ! -iname ".*" \) | xargs grep -c "qualifier=" | sed "s/.*:\(.*\)/\1/g" | paste -sd+ | bc`

echo "Total of qualifier=\"\": $NQ".

#############################
# total of qualifier="seq" attribute
#############################

NQS=`find . -type f \( -iname "*.ncl" ! -iname ".*" \) | xargs grep -c "qualifier=\"seq\"" | sed "s/.*:\(.*\)/\1/g" | paste -sd+ | bc`

echo "Total of qualifier=\"seq\": $NQS/$NQ."

#############################
# total of qualifier="par" attribute
#############################

NQP=`find . -type f \( -iname "*.ncl" ! -iname ".*" \) | xargs grep -c "qualifier=\"par\"" | sed "s/.*:\(.*\)/\1/g" | paste -sd+ | bc`

echo "Total of qualifier=\"par\": $NQP/$NQ."

#############################
# total of qualifier="and" attribute
#############################

NQA=`find . -type f \( -iname "*.ncl" ! -iname ".*" \) | xargs grep -c "qualifier=\"and\"" | sed "s/.*:\(.*\)/\1/g" | paste -sd+ | bc`

echo "Total of qualifier=\"and\": $NQA/$NQ."

#############################
# total of qualifier="or" attribute
#############################

NQO=`find . -type f \( -iname "*.ncl" ! -iname ".*" \) | xargs grep -c "qualifier=\"or\"" | sed "s/.*:\(.*\)/\1/g" | paste -sd+ | bc`

echo "Total of qualifier=\"or\": $NQO/$NQ."
echo

#############################
# total of width="" attribute
#############################

NWIDTH=`find . -type f \( -iname "*.ncl" ! -iname ".*" \) | xargs grep -c "width=" | sed "s/.*:\(.*\)/\1/g" | paste -sd+ | bc`

echo "Total of width=\"\" attribute: $NWIDTH".

#############################
# total of width="100%" attribute
#############################

NWIDTH100=`find . -type f \( -iname "*.ncl" ! -iname ".*" \) | xargs grep -c "width=\"100%\"" | sed "s/.*:\(.*\)/\1/g" | paste -sd+ | bc`

echo "Total of width=\"\" attribute: $NWIDTH100/$NWIDTH".
echo

#############################
# total of height="" attribute
#############################

NHEIGHT=`find . -type f \( -iname "*.ncl" ! -iname ".*" \) | xargs grep -c "height=" | sed "s/.*:\(.*\)/\1/g" | paste -sd+ | bc`

echo "Total of height=\"\" attribute: $NHEIGHT".

#############################
# total of height="100%" attribute
#############################

NHEIGHT100=`find . -type f \( -iname "*.ncl" ! -iname ".*" \) | xargs grep -c "height=\"100%\"" | sed "s/.*:\(.*\)/\1/g" | paste -sd+ | bc`

echo "Total of height=\"\" attribute: $NHEIGHT100/$NHEIGHT".
echo

#############################
# total of <switch>
#############################

NSW=`find . -type f \( -iname "*.ncl" ! -iname ".*" \) | xargs grep -c "<switch" | sed "s/.*:\(.*\)/\1/g" | paste -sd+ | bc`

echo "Total of <switch> element: $NSW".

#############################
# total of <descriptorSwitch>
#############################

NDSW=`find . -type f \( -iname "*.ncl" ! -iname ".*" \) | xargs grep -c "<descriptorSwitch" | sed "s/.*:\(.*\)/\1/g" | paste -sd+ | bc`

echo "Total of <descriptorSwitch> element: $NDSW".

#############################
# total of <defaultComponent>
#############################

NDC=`find . -type f \( -iname "*.ncl" ! -iname ".*" \) | xargs grep -c "<defaultComponent" | sed "s/.*:\(.*\)/\1/g" | paste -sd+ | bc`

echo "Total of <defaultComponent> element: $NDC/($NSW+$NDSW)".
echo

#############################
# total of operator="" attribute
#############################

NO=`find . -type f \( -iname "*.ncl" ! -iname ".*" \) | xargs grep -c "operator=" | sed "s/.*:\(.*\)/\1/g" | paste -sd+ | bc`

echo "Total of operator=\"\": $NO".

#############################
# total of operator="seq" attribute
#############################

NOS=`find . -type f \( -iname "*.ncl" ! -iname ".*" \) | xargs grep -c "operator=\"seq\"" | sed "s/.*:\(.*\)/\1/g" | paste -sd+ | bc`

echo "Total of operator=\"seq\": $NOS/$NO."

#############################
# total of operator="par" attribute
#############################

NOP=`find . -type f \( -iname "*.ncl" ! -iname ".*" \) | xargs grep -c "operator=\"par\"" | sed "s/.*:\(.*\)/\1/g" | paste -sd+ | bc`

echo "Total of operator=\"par\": $NOP/$NO."

#############################
# total of operator="and" attribute
#############################

NOA=`find . -type f \( -iname "*.ncl" ! -iname ".*" \) | xargs grep -c "operator=\"and\"" | sed "s/.*:\(.*\)/\1/g" | paste -sd+ | bc`

echo "Total of operator=\"and\": $NOA/$NO."

#############################
# total of operator="or" attribute
#############################

NOO=`find . -type f \( -iname "*.ncl" ! -iname ".*" \) | xargs grep -c "operator=\"or\"" | sed "s/.*:\(.*\)/\1/g" | paste -sd+ | bc`

echo "Total of operator=\"or\": $NOO/$NO."
echo
